site_name: Climate Tools Workshop
site_description: "Workshop: Introduction to DHIS2 climate tools"

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.sections
    - navigation.expand
    - navigation.top
    - navigation.tracking
    - search.highlight
    - content.code.copy

nav:
  - Home: index.md
  - Guides:
      - Setup: guides/setup.md
      - DHIS2 Python Client: guides/dhis2-client.md
      - Earth Observation: guides/dhis2eo.md

markdown_extensions:
  - admonition
  - attr_list
  - def_list
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true

plugins:
  - search
