id: cambodia.opd.ig
canonical: http://example.org/fhir/cambodia-opd
name: CambodiaOPDIG
title: Cambodia OPD FHIR Implementation Guide
description: FHIR IG for Cambodia DHIS2 Outpatient Consultation
status: draft
version: 0.1.0
fhirVersion: 4.0.1
copyrightYear: 2026+
releaseLabel: ci-build
license: CC0-1.0
publisher:
  name: Workshop Participant
  url: http://example.org

menu:
  Home: index.html
  Artifacts: artifacts.html
